USE customer_behavior;

SELECT TOP 10 *
FROM dbo.customer;

--1 What is the total revenue generated by male versus female customers?

select gender,
sum(purchase_amount) as revenue
from dbo.customer
group by gender;

--2 Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from dbo.customer
where discount_applied ='Yes' and purchase_amount >= ( select avg(purchase_amount) from dbo.customer);



--3 What are the top five products with the highest average review rating?

Select top 5 item_purchased,Round(avg(review_rating),2) avg_review_rating
from dbo.customer
group by item_purchased
order by avg(review_rating) desc;


--4 Compare the average purchase amount between standard and express shipping.

select shipping_type,avg(purchase_amount) as avg_amount
from dbo.customer
where shipping_type in ('standard','Express')
group by shipping_type;

--5 Do subscribed customers spend more (compare average spend and 
--total revenue between subscriber and non-subscriber)?

select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from dbo.customer
group by subscription_status;

--6 Which five products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased,
ROUND(100* sum(case when discount_applied= 'Yes' then 1 else 0 end)/ count(*),2) as discount_rate
from dbo.customer
group by item_purchased
order by discount_rate desc;

--7 Segment customers into new, returning, and loyal based on total previous purchases show count of each segment.

With customer_type as (
select
customer_id,
previous_purchases,
case when previous_purchases=1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from dbo.customer
)

select customer_segment, count(*) as number_of_customers
from customer_type
GROUP BY customer_segment
 order by number_of_customers desc;

--8 What are the top three most purchased products within each category?

with most_purchased_product as (
select  item_purchased,
category,
Row_number() over (partition by category order by count(customer_id) desc) item_rank,
count(customer_id) total_order
from dbo.customer
group by item_purchased,category)

select item_purchased,item_rank,category,total_order
from most_purchased_product
where item_rank<=3


--9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) repeated_buyers
from dbo.customer
where previous_purchases >5
group by subscription_status

--10 What is the total revenue by age group?

select
age_group,
sum(purchase_amount) total_revenue
from dbo.customer
group by age_group
order by total_revenue desc;